### ISSUE TITLE
Messages don't render/load in.

### ISSUE THREAD

**Issue by zkxjzmswkwl** [traumatism/ToastCord#4]
The messages send, but no messages render.

Tried logging the received messages in the async loop over messages and got nothing back.

**Comment by lhitori** [comment]
Tried the last version (From Git) on a Google Cloud Shell, message sending works fine.

DM me on Discord.

**Comment by zkxjzmswkwl** [comment]
Dm'd more information and you solved it same-day.

Awesome job, thank you!
