### ISSUE TITLE
is it possible to fetch images / image url? 

### ISSUE THREAD

**Issue by Newkindaspecial** [traumatism/ToastCord#7]
Is it possible to get the image or image url for images posted to channels? Currently it just seems to return an empty string for message content.

**Comment by lhitori** [comment]
this project is deprecated.

you could try to test if the return content when it fetches message contains embed/attachments and try to parse it.

**Comment by Newkindaspecial** [comment]
Oh my apologies and you're right. It's there under 'attachments' tysm
